version: '3'

services:
  db:
    image: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
  app:
    build: .
    command: python3 manage.py runserver
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  postgres_data: