# Generated by Django 5.1.6 on 2025-02-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('has_text_answer', models.BooleanField(default=False, verbose_name='Текстовый ответ')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answeroption', verbose_name='Выбранный ответ')),
            ],
        ),
    ]
